
spring:
  application:
    name: actuator
  config:
    import: optional:configserver:${CONFIG_SERVER_URI}
  cloud:
    config:
      username: ${CONFIG_SERVER_USERNAME}
      password: ${CONFIG_SERVER_PASSWORD}

