server:
  port: 9000

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: git@github.com:moset1/SubSite-congif.git
          ignoreLocalSshSettings: true
          private-key: ${SPRING_CLOUD_CONFIG_SERVER_GIT_PRIVATE_KEY}