server:
  port: 0 # Start on a random port

spring:
  application:
    name: subscription-service

  # --- Database Configuration (replace with your actual values) ---
  # datasource:
  #   url: jdbc:mysql://localhost:3306/subscription_db?useSSL=false&serverTimezone=UTC
  #   username: your-username
  #   password: your-password
  # jpa:
  #   hibernate:
  #     ddl-auto: update
  #   show-sql: true

  # --- RabbitMQ Configuration (replace with your actual values) ---
  # rabbitmq:
  #   host: localhost
  #   port: 5672
  #   username: guest
  #   password: guest

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.semocompany.subscriptionservice: DEBUG