
server:
  port: 0

spring:
  application:
    name: subscription
  config:
    import: optional:configserver:${CONFIG_SERVER_URI}
  cloud:
    config:
      username: ${CONFIG_SERVER_USERNAME}
      password: ${CONFIG_SERVER_PASSWORD}


# Eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka_server_username}:${eureka_server_password}@localhost:8761/eureka