name: config-server-ci.yml

on:
  push:
    branches: ["main"]
    paths:
      - 'SubSiteConfigServer/**'

  pull_request:
    branches: ["main"]
    paths:
      - 'SubSiteConfigServer/**'


jobs:
  build:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x SubSiteConfigServer/gradlew

      - name: Build with Gradle
        run: ./SubSiteConfigServer/gradlew -p SubSiteConfigServer clean build

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: config-server-jar
          path: SubSiteConfigServer/build/libs/*.jar

  docker-push:

    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: config-server-jar
          path: SubSiteConfigServer/build/libs/

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./SubSiteConfigServer
          push: true
          tags: moset1/subsite-config-service:${{ github.sha }}

  deploy:

    needs: docker-push
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Deploy to GCP Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USERNAME }}
          key: ${{ secrets.GCP_PRIVATE_KEY }}
          passphrase: ${{ secrets.GCP_SSH_PASSPHRASE }}

          script: |
            docker pull moset1/subsite-config-service:${{ github.sha }}
            
            docker stop config-service-container || true
            docker rm config-service-container || true
            
            docker run -d --name config-service-container -p 9000:9000 \
            -e "SPRING_SECURITY_USER_NAME=${{ secrets.CONFIG_SERVER_USERNAME }}" \
            -e "SPRING_SECURITY_USER_PASSWORD=${{ secrets.CONFIG_SERVER_PASSWORD }}" \
            -e "SPRING_CLOUD_CONFIG_SERVER_GIT_PRIVATE_KEY=${{ secrets.SPRING_CLOUD_CONFIG_SERVER_GIT_PRIVATE_KEY }}" \
              moset1/subsite-config-service:${{ github.sha }}