name: eureka-server-ci.yml

on:
  push:
    branches: ["main"]
    paths:
      - 'SubSiteEurekaServer/**'

  pull_request:
    branches: ["main"]
    paths:
      - 'SubSiteEurekaServer/**'


jobs:
  build:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x SubSiteEurekaServer/gradlew

      - name: Build with Gradle
        run: ./SubSiteEurekaServer/gradlew -p SubSiteEurekaServer clean build

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: eureka-server-jar
          path: SubSiteEurekaServer/build/libs/*.jar

  docker-push:

    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: eureka-server-jar
          path: SubSiteEurekaServer/build/libs/

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./SubSiteEurekaServer
          push: true
          tags: moset1/subsite-eureka-service:${{ github.sha }}

  deploy:

    needs: docker-push
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Deploy to EC2 Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USERNAME }}
          key: ${{ secrets.GCP_PRIVATE_KEY }}

          script: |
            docker pull moset1/subsite-eureka-service:${{ github.sha }}
            
            docker stop eureka-service-container || true
            docker rm eureka-service-container || true
            
            docker run -d --name eureka-service-container -p 8761:8761 \
            -e "SPRING_SECURITY_USER_NAME=${{ secrets.EUREKA_SERVER_USERNAME }}" \
            -e "SPRING_SECURITY_USER_PASSWORD=${{ secrets.EUREKA_SERVER_PASSWORD }}" \
              moset1/subsite-eureka-service:${{ github.sha }}